spring.application.name=booking-system
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.datasource.hikari.maximum-pool-size=35
spring.datasource.hikari.connection-timeout=30000
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-service